// podlets/vue-pod/src/App.vue
<script setup>
import { ref, onMounted, onBeforeUnmount } from "vue";
import { globalCounterSub } from "../__services__/message.service";

defineProps({
	count: Number,
});

const count = ref(0);
const globalCounter = globalCounterSub("svelte-pod");
let subscription;

onMounted(() => {
	subscription = globalCounter.subscribe((n) => (count.value = n));
});
onBeforeUnmount(() => subscription.unsubscribe);

const decrement = () => globalCounter.update((n) => --n);
const increment = () => globalCounter.update((n) => ++n);
</script>

<template>
	<article class="Vue">
		<button class="decrement" type="button" @click="decrement">&ndash;</button>
		<div class="number">{{ count }}</div>
		<button class="increment" type="button" @click="increment">+</button>
	</article>
</template>

// podlets/react-pod/src/App.jsx
import React, { useEffect, useState } from "react";
import { globalCounterSub } from "../__services__/message.service";

function App() {
	const [count, setCount] = useState(0);
	const globalCounter = globalCounterSub("react-pod");

	useEffect(() => {
		const subscription = globalCounter.subscribe((n) => setCount(n));
		return subscription.unsubscribe;
	}, []);

	const decrement = () => globalCounter.update((n) => --n);
	const increment = () => globalCounter.update((n) => ++n);

	return (
		<article className="React">
			<button className="decrement" type="button" onClick={decrement}>
				&ndash;
			</button>
			<div className="number">{count}</div>
			<button className="increment" type="button" onClick={increment}>
				+
			</button>
		</article>
	);
}

export default App;
