// podlets/react-pod/src/App.jsx
import React, { useEffect, useState } from "react";
import { globalCounterSub } from "../__services__/message.service";

function App() {
	const [count, setCount] = useState(0);
	const globalCounter = globalCounterSub("react-pod");

	useEffect(() => {
		const subscription = globalCounter.subscribe((n) => setCount(n));
		return subscription.unsubscribe;
	}, []);

	const decrement = () => globalCounter.update((n) => --n);
	const increment = () => globalCounter.update((n) => ++n);

	return (
		<article className="React">
			<button className="decrement" type="button" onClick={decrement}>
				&ndash;
			</button>
			<div className="number">{count}</div>
			<button className="increment" type="button" onClick={increment}>
				+
			</button>
		</article>
	);
}

export default App;

// podlets/svelte-pod/src/App.svelte
<script>
	import { globalCounterSub } from "../../__services__/message.service";

	const count = globalCounterSub("svelte-pod");
	const decrement = () => count.update((n) => --n);
	const increment = () => count.update((n) => ++n);
</script>

<article class="Svelte">
	<button class="decrement" type="button" on:click={decrement}>&ndash;</button>
	<div class="number">{$count}</div>
	<button class="increment" type="button" on:click={increment}>+</button>
</article>
